# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 633bd830eff21f1463c249e3a7b52d12a12dffa52e346f0fbdd59ef46cb918da4cf539efdd3bd89c6514c409ac014f5a8eb21276ccd38394cc2b12a467b0b0c1

test:
  secret_key_base: bbae79e141cea4d8d0e3544dd8a7e35e5f973adc0b7e48f3e8b1cafc5430ab9344577c381b1cd4fcefceab06ce4be25245cd5dd08ab94b2d7c540d2ded59e6ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
